"""create_review_images_table

Revision ID: 8ec5e4af4626
Revises: 984ed45fbfc2
Create Date: 2022-12-10 03:17:37.423258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec5e4af4626'
down_revision = '984ed45fbfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_foreign_key("None", 'users', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('None', type_='foreignkey')

    # ### end Alembic commands ###
