"""Initial migration.

Revision ID: 6ae124cccc6d
Revises:
Create Date: 2022-12-09 12:05:05.542357

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")

# revision identifiers, used by Alembic.
revision = '6ae124cccc6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('display_name', sa.VARCHAR(
                        length=100), nullable=False),
                    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('hashed_password', sa.TEXT(), nullable=False),
                    sa.Column('profile_picture_url', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )

    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('seller_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=140), nullable=False),
                    sa.Column('price', sa.DECIMAL(), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['users.id'], name='fk_product_seller_id'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('product_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.TEXT(), nullable=False),
                    sa.Column('preview', sa.BOOLEAN(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['products.id'], name='fk_product_image_product_id'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('buyer_id', sa.Integer(), nullable=False),
                    sa.Column('seller_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('review', sa.VARCHAR(
                        length=840), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['buyer_id'], ['users.id'], name='fk_review_buyer_id'),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['products.id'], name='fk_review_product_id'),
                    sa.ForeignKeyConstraint(
                        ['seller_id'], ['users.id'], name='fk_review_seller_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('product_images')
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###
